### ISSUE TITLE
Multi Type ActionParameterValue 

### ISSUE THREAD

**Issue by bekirbostanci** [kKdH/vda5050-types-rs#1]
I had a problem with single type of action parameters because for initPosition at least you need float, so I checked a bit and I found this solution but I **am not rust expert** so just suggestion :) 
```
/// ActionParameter Object
#[serde_with::skip_serializing_none]
#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ActionParameter {
    /// The key of the action parameter. For example, duration, direction, signal.
    pub key: String,
    /// The value of the action parameter. For example: 103.2, "left", true, [1, 2, 3].
    pub value: ActionParameterValue,
}

/// Enum to represent the possible types for the value of an action parameter.
#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(untagged)]
pub enum ActionParameterValue {
    /// Represents an integer value.
    Int(i32),
    Float(f64),
    /// Represents a string value.
    Str(String),
}
```

https://github.com/kKdH/vda5050-types-rs/blob/16e0289c4a2550951412925fa8dc392616e37e3e/src/action.rs#L48C16-L48C22

**Comment by kKdH** [comment]
Hey @bekirbostanci,

thank you for your suggestion. I already considered a solution like that which works for primitive types quite well. However, a problem arises because VDA5050 also allows arrays and objects as parameter types and in that cases i cannot known the exact type to deserialize.

If it satisfies your needs i can provide the following solution:

```rust
pub enum ActionParameterValue {
    Int(i32),
    Float(f32),
    String(String),
    Object(Vec<u8>),
    Array(Vec<u8>),
}
```

In the case of an array or object, a crate user (master control or AGV) can deserialize the bytes on its own, because it has more context information (e.g. the key indicates which type the parameter has to have).

**Comment by kKdH** [comment]
For completeness, 021b7df introduces the proposed solution.
